services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  
    extra_hosts:
      - "host.docker.internal:host-gateway"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  discountdb:
    container_name: discountdb
    environment : 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"

  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "Str0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - orderdb_data:/var/opt/mssql 
    ports:
      - "1433:1433" 
    healthcheck:
       test: ["CMD-SHELL","/opt/mssql-tools/bin/sqlcmd -S orderdb -U sa -P 'Str0ngP@ssw0rd!' -Q 'select 1'"]
       interval: 10s
       timeout: 10s
       retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"  
    depends_on:
      - "catalogdb"
    ports:
      - "8000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379" 
      - "GrpcSettings__DiscountUrl=http://discount.api:8080" 
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200" 
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=root;"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200" 
    depends_on:
      discountdb:
        condition: service_healthy
    ports:
      - "8002:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Str0ngP@ssw0rd!;TrustServerCertificate=True;"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200" 
    depends_on:
     - orderdb                    
     - rabbitmq
    ports:
      - "8003:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ocelot.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8010:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    extra_hosts:
      - "host.docker.internal:host-gateway"